# Generated by Django 4.2.3 on 2026-09-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Master_Tables', '0002_alter_usermaster_account_type'),
        ('Api_Transactions_Tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Api_Master_Tables.usermaster'),
        ),
    ]
