# Generated by Django 4.2.3 on 2026-06-15 11:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Api_Master_Tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('order_id', models.PositiveIntegerField(default=1, editable=False)),
                ('time', models.TimeField(auto_now_add=True)),
                ('total_sale_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cash_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_id', models.PositiveIntegerField(default=1, editable=False)),
                ('time', models.TimeField(auto_now_add=True)),
                ('amount_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_Transactions_Tables.ordersummary')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_Master_Tables.paymentmodemaster')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('order_details_id', models.PositiveIntegerField(default=1, editable=False)),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sale_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_rupees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Api_Transactions_Tables.ordersummary')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_Master_Tables.productmaster')),
            ],
        ),
    ]
