# Generated by Django 4.2.3 on 2026-06-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Transactions_Tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='product_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
