# Generated by Django 4.2.3 on 2026-09-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Master_Tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='account_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Standard', 'Standard')], default='Standard', max_length=20),
        ),
    ]
