# Generated by Django 4.2.3 on 2026-09-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Master_Tables', '0002_alter_usermaster_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMaster',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Master',
                'verbose_name_plural': 'Admin Masters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Api_Master_Tables.usermaster',),
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
            ],
            options={
                'verbose_name': 'Customer Master',
                'verbose_name_plural': 'Customer Masters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Api_Master_Tables.usermaster',),
        ),
    ]
